---
- name: Demo passwordless setup
  hosts: hmcs
  connection: local

  tasks:
    - name: Share private key to hmc for passwordless login
      ansible.builtin.shell:
        cmd: |
            key=`head -n 1 ~/.ssh/id_rsa.pub`
            sshpass -p {{ hmc_password }} ssh  {{ ansible_user }}@{{ inventory_hostname }} mkauthkeys -a "'$key'"
      register: private_key
      changed_when: private_key.rc == 0
